# Generated by Django 4.2.1 on 2023-07-05 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 10, 30, 32, 851867)),
        ),
    ]
